[package]
name = "open_albion"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
winit = "0.30.12"
fable_data = { path = "../fable_data" }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.22", features = [ "env-filter", "std" ] }
pollster = "0.4.0"
derive_more = { version = "2.0.1", features = ["error", "display"] }
argh = "0.1.13"

[dependencies.wgpu]
version = "27.0.1"
