[package]
name = "open_albion"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
winit = "0.30.12"
fable_data = { path = "../fable_data" }
tracing = "0.1.41"
tracing-log = "0.2.0"
tracing-tracy = "0.11.4"
tracing-subscriber = "0.3.19"
pollster = "0.4.0"
derive_more = { version = "2.0.1", features = ["error", "display"] }
env_logger = "0.11.8"

[dependencies.wgpu]
version = "27.0.1"
