[package]
name = "fable_data"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
bcndecode = "0.2.0"
derive_more = { version = "1.0.0", features = ["from", "display", "error"] }
fallible-iterator = "0.3.0"
serde = { version = "1.0.210", features = ["derive"] }
minilzo = { path = "../minilzo_rust" }

[dependencies.bytemuck]
features = ["derive", "extern_crate_std"]
version = "1.16.3"
